version: "3"
volumes:
    prometheus_data: {}
    grafana_data: {}    
services:
  backtest:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: backtest
    restart: on-failure
    ports:
      - 6061:6061
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade 
      --logfile /freqtrade/user_data/logs/backtest.log
      --db-url sqlite:////freqtrade/user_data/backtest.sqlite
      --config /freqtrade/user_data/backtest.json
      --strategy Combined_NFIv6_SMA
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config.json --config /freqtrade/user_data/dev_env/config_dev_1.json ping | grep -q pong"]
      interval: 30s
      timeout: 4s
      retries: 3
