version: "3"
volumes:
    prometheus_data: {}
    grafana_data: {}    
services:
  freqtrade1:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade1
    restart: on-failure
    ports:
      - 8081:8081
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade 
      --logfile /freqtrade/user_data/logs/freqtrade_1.log
      --db-url sqlite:////freqtrade/user_data/dev_1.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/dev_env/config_dev_1.json
      --strategy Combined_NFIv6_SMA
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config.json --config /freqtrade/user_data/dev_env/config_dev_1.json ping | grep -q pong"]
      interval: 30s
      timeout: 4s
      retries: 3
  freqtrade2:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade2
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade 
      --logfile /freqtrade/user_data/logs/freqtrade_2.log
      --db-url sqlite:////freqtrade/user_data/dev_2.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/dev_env/config_dev_2.json
      --strategy BigZ04
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config.json --config /freqtrade/user_data/dev_env/config_dev_2.json ping | grep -q pong"]
      interval: 30s
      timeout: 4s
      retries: 3
  freqtrade3:
    build:
      context: .
      dockerfile: "./docker/Dockerfile.custom"
    container_name: freqtrade3
    restart: on-failure
    ports:
      - 8083:8083
    volumes:
      - ./user_data:/freqtrade/user_data
    command: >
      trade 
      --logfile /freqtrade/user_data/logs/freqtrade_3.log
      --db-url sqlite:////freqtrade/user_data/dev_3.sqlite
      --config /freqtrade/user_data/config.json
      --config /freqtrade/user_data/dev_env/config_dev_3.json
      --strategy CombinedBinHClucAndMADV9
    healthcheck:
      test: ["CMD-SHELL", "python3 /freqtrade/scripts/rest_client.py --config /freqtrade/user_data/config.json --config /freqtrade/user_data/dev_env/config_dev_3.json ping | grep -q pong"]
      interval: 30s
      timeout: 4s
      retries: 3
  ftmetric1:
    image: ghcr.io/kamontat/ftmetric:v4.3.0
    container_name: ftmetric1
    restart: on-failure
    ports:
      - 8091:8091
    environment:
      - FTH_FREQTRADE__URL=http://freqtrade1:8081
      - FTH_FREQTRADE__USERNAME=freqtrader
      - FTH_FREQTRADE__PASSWORD=secret
      - FTH_SERVER__PORT=8091
      - FTH_FREQTRADE__CLUSTER=1A
    command: --no-env-file
    depends_on:
      - freqtrade1
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8091/version"]
      interval: 1m
      timeout: 1s
      retries: 3
  ftmetric2:
    image: ghcr.io/kamontat/ftmetric:v4.3.0
    container_name: ftmetric2
    restart: on-failure
    ports:
      - 8092:8092    
    environment:
      - FTH_FREQTRADE__URL=http://freqtrade2:8082
      - FTH_FREQTRADE__USERNAME=freqtrader
      - FTH_FREQTRADE__PASSWORD=secret
      - FTH_SERVER__PORT=8092
      - FTH_FREQTRADE__CLUSTER=2A
    command: --no-env-file
    depends_on:
      - freqtrade2
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8092/version"]
      interval: 1m
      timeout: 1s
      retries: 3
  ftmetric3:
    image: ghcr.io/kamontat/ftmetric:v4.3.0
    container_name: ftmetric3
    restart: on-failure
    ports:
      - 8093:8093    
    environment:
      - FTH_FREQTRADE__URL=http://freqtrade3:8083
      - FTH_FREQTRADE__USERNAME=freqtrader
      - FTH_FREQTRADE__PASSWORD=secret
      - FTH_SERVER__PORT=8093
      - FTH_FREQTRADE__CLUSTER=3A
    command: --no-env-file
    depends_on:
      - freqtrade3
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8093/version"]
      interval: 1m
      timeout: 1s
      retries: 3
  prometheus:
    image: prom/prometheus:latest
    restart: on-failure
    container_name: prometheus
    # be aware before open the port
    ports:
       - 9090:9090
    volumes:
      # you can config prometheus via this directory (prometheus.yml)
       - ./prometheus/config:/etc/prometheus/
       - prometheus_data:/prometheus
    depends_on:
      - ftmetric1
      - ftmetric2
      - ftmetric3            
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 1m
      timeout: 1s
      retries: 3
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: on-failure
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:  
      - prometheus
    environment:
      ## override server url
      # - GF_SERVER_ROOT_URL=http://example.com
      - GF_SERVER_HTTP_PORT=3000
      ## enabled grafana beta alert manager
      # - GF_FEATURE_TOGGLES_ENABLE=ngalert
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=verygrafanapassword
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 1m
      timeout: 1s
      retries: 3
